//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum DirectionType {
        
        /// Type of signal is Read.
        Read,
        
        /// Type of signal is ReadWrite.
        ReadWrite,
        
        /// Type of signal is Write.
        Write,
    }
}
