//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// A generic equivalent for an energy supplier on a transmission or distribution voltage level.
    public class EnergySource : ConductingEquipment {
        
        /// High voltage source load.
        private System.Single? cim_activePower;
        
        private const bool isActivePowerMandatory = false;
        
        private const string _activePowerPrefix = "cim";
        
        /// Phase-to-phase nominal voltage.
        private System.Single? cim_nominalVoltage;
        
        private const bool isNominalVoltageMandatory = false;
        
        private const string _nominalVoltagePrefix = "cim";
        
        public virtual float ActivePower {
            get {
                return this.cim_activePower.GetValueOrDefault();
            }
            set {
                this.cim_activePower = value;
            }
        }
        
        public virtual bool ActivePowerHasValue {
            get {
                return this.cim_activePower != null;
            }
        }
        
        public static bool IsActivePowerMandatory {
            get {
                return isActivePowerMandatory;
            }
        }
        
        public static string ActivePowerPrefix {
            get {
                return _activePowerPrefix;
            }
        }
        
        public virtual float NominalVoltage {
            get {
                return this.cim_nominalVoltage.GetValueOrDefault();
            }
            set {
                this.cim_nominalVoltage = value;
            }
        }
        
        public virtual bool NominalVoltageHasValue {
            get {
                return this.cim_nominalVoltage != null;
            }
        }
        
        public static bool IsNominalVoltageMandatory {
            get {
                return isNominalVoltageMandatory;
            }
        }
        
        public static string NominalVoltagePrefix {
            get {
                return _nominalVoltagePrefix;
            }
        }
    }
}
