//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// The parts of a power system that are physical devices, electronic or mechanical.
    public class Equipment : PowerSystemResource {
        
        private System.Boolean? cim_normallyInService;
        
        private const bool isNormallyInServiceMandatory = false;
        
        private const string _normallyInServicePrefix = "cim";
        
        public virtual bool NormallyInService {
            get {
                return this.cim_normallyInService.GetValueOrDefault();
            }
            set {
                this.cim_normallyInService = value;
            }
        }
        
        public virtual bool NormallyInServiceHasValue {
            get {
                return this.cim_normallyInService != null;
            }
        }
        
        public static bool IsNormallyInServiceMandatory {
            get {
                return isNormallyInServiceMandatory;
            }
        }
        
        public static string NormallyInServicePrefix {
            get {
                return _normallyInServicePrefix;
            }
        }
    }
}
